### ISSUE TITLE
Cross browser compatability

### ISSUE THREAD

**Issue by edwinphillips** [willsweb/babbby#22]

**Comment by willsweb** [comment]
The site partially functions on all browsers, but not entirely on any. Mostly to do with the music and video players. Recently Ubuntu would start playing the music, and properly randomly select one after the other, but no information about the tracks. Currently ios scrolls the text but doesnt play any audio or video. These things may be less to do with browser compatability and more just to do with the player engine. Most other functionality does seem to work across different platforms.
